### ISSUE TITLE
Tests with integration_test

### ISSUE THREAD

**Issue by nilsreichardt** [VGVentures/happy_testing#2]
## Description
I would love to see some tests with the new `integration_test` package 😍

```yaml
dev_dependencies:
  integration_test:
    sdk: flutter
```

https://pub.dev/packages/integration_test
https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e
